### ISSUE TITLE
Alert dialog on opening of class activity sheets

### ISSUE THREAD

**Issue by tjnelson5** [amyrebecca/zootools-sheets#18]
Add an alert or custom dialog on opening of each class activity sheet.  The text should inform students that the sheet is read-only and that they must make a copy of the sheet to work on.  If possible, a button that executes the "Make a copy..." command would be great so that it can be done right from the dialog.

Want to test with different amounts of text to see if providing some basic instructions in the alert box is feasible.

May want different text for each activity - script should be separate from tools?

https://developers.google.com/apps-script/guides/dialogs

**Comment by srallen** [comment]
This is done for the four pilot activities
