### ISSUE TITLE
Summary statistics sidebar

### ISSUE THREAD

**Issue by amy-langley** [amyrebecca/zootools-sheets#2]
- [x] Calculate min, max, mean, and standard deviation
- [x] Allow user to add an arbitrary number of variable summaries
- [ ] Allow user to remove variable summaries
- [x] Allow user to output values to a new sheet

**Comment by srallen** [comment]
I didn't realize adding an arbitrary number of summary stats was a feature request. @tjnelson5 is this still wanted?

**Comment by srallen** [comment]
Closing for now since add-on is in production and can reopen a separate feature request issue if an arbitrary number of summary stats is wanted.
