### ISSUE TITLE
Student location survey, potential bug

### ISSUE THREAD

**Issue by trouille** [amyrebecca/zootools-sheets#26]
Note; using chrome

I saw in ZooTools you could choose 'Student Location Survey', so I did. I inputted institution and from location, and got this error:

"Something went wrong: ScriptError: You do not have permission to perform that action."

Not sure if this is where students would input 'Student Location Survey' responses, but if so, then it's a bug to follow up on.

**Comment by srallen** [comment]
The `Protection` class ended up being much more complicated than I expected. Basically, the document owner can always edit and I can programmatically add a protection to a sheet or range. Being able to edit the protection's permissions defaults to the spreadsheet's default permissions, which in this case it is anyone who has the link. Or I can programmatically remove editors of the protection, which I was doing, but for some reason I had issues with adding editors back when it needed to be removed (i.e. when someone was submitting the survey). A user that doesn't have permission to edit the protection can't remove it. 

Anyway for now, the sheet is protected, but by warning only. This will need to be looked at again later.
