### ISSUE TITLE
Scatter Plot Helper - seeing trend line values

### ISSUE THREAD

**Issue by trouille** [amyrebecca/zootools-sheets#27]
Note: in chrome

Using the scatter plot helper, I created a plot, added the linear trendline, and clicked 'send to sheet'. I wanted to see the y=mx+b values as a label, but it's not there. Even if I click on 'advanced edit', I can't seem to get the label to pop up. 

(On a regular google sheet, if I make a scatter plot and add a trendline, you can have the y=mx+b equation used as the label under the 'customization' tab in advanced edit). 

Need to double check with Tommy, but I can imagine for other activities and/or for the research, we'll want to allow students to see what the actual trendline equation is.

**Comment by srallen** [comment]
@tjnelson5, could you respond to @trouille's suggestion? Thanks.

**Comment by srallen** [comment]
Also, it's not a bug. I don't have the option set in the preview to add the label. 

In the advanced edit in sheets itself, it's an option in customization under label: 
<img width="346" alt="screen shot 2016-01-19 at 9 24 50 am" src="https://cloud.githubusercontent.com/assets/5016731/12422880/9c9f2a06-be8e-11e5-8dbf-bbbe6188ff9b.png">

The label shows up as a tooltip when you hover on the trendline.

**Comment by tjnelson5** [comment]
Hi @srallen and @trouille.  We plan to use the trendline information in the Hubble's Law activity.  So we will need to be able to access the trendline information this semester, although I expect we won't need it within the next month.  I'll be finalizing the schedule for the in-class activities next week while I'm in Minnesota.
