### ISSUE TITLE
Safari testing notes

### ISSUE THREAD

**Issue by mcbouslog** [amyrebecca/zootools-sheets#28]
error on load of Scatter Plot, Histogram and Summary Stats Helpers (tools load, but are not usable/calculating):

`[Error] Error while parsing the 'sandbox' attribute: 'allow-modals', 'allow-popups-to-escape-sandbox' are invalid sandbox flags. (iframedAppPanel, line 14)`
`[Warning] Unexpected CSS token: -moz-box-sizing (userCodeAppPanel, line 81)`
`[Error] SyntaxError: DOM Exception 12: An invalid or illegal string was specified.
    querySelectorAll
    showStatus
    getVariables
    (anonymous function)
    write
    Fj
    (anonymous function)
    sh
    nh
    (anonymous function)`

**Comment by mcbouslog** [comment]
on Map Tool load the following console error:
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (kh, line 0`
`[Warning] SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages (util.js, line 30)`
BUT tool works (shows locations on map)

**Comment by srallen** [comment]
The API warning can be ignored.
