### ISSUE TITLE
Filter data helper

### ISSUE THREAD

**Issue by trouille** [amyrebecca/zootools-sheets#42]
Add user-friendly functionality for students to filter the data based on different characteristics. For example, filter for galaxies with V-B<0.5.

**Comment by trouille** [comment]
Deadline of July 1st, so students can pilot test the research project experience during first 3 weeks of July.

**Comment by trouille** [comment]
@tjnelson5 post here other example cases. Thanks!

**Comment by tjnelson5** [comment]
We also want: selection on categorical data (Morphology == "Spiral" etc), and capability to combine filters (AND/OR operator required for this).

**Comment by tjnelson5** [comment]
Once filters are applied, a new sheet should appear with the filtered dataset (lets plan on copying over all columns for rows that meet the filters)

**Comment by tjnelson5** [comment]
Decimal input not being recognized as numbers by regex.
