### ISSUE TITLE
Filter data helper: requested enhancement in pulling out filtered data

### ISSUE THREAD

**Issue by tjnelson5** [amyrebecca/zootools-sheets#45]
Right now, when data is filtered, only the filtered column is inserted into the filtered data tab. Is it possible to filter the entire dataset and copy over all columns for the rows that meet the filter?

For example, if we filter on type = elliptical, it would be great to get all columns for every elliptical galaxy.

**Comment by srallen** [comment]
I'm investigating this. We'll probably need a toggle for this in the interface to trigger a slightly different query to be built.
