### ISSUE TITLE
Scatterplot tool not grabbing the correct number of entries

### ISSUE THREAD

**Issue by codydirks** [amyrebecca/zootools-sheets#51]
The scatterplot tool sometimes fails to correctly show all entries when creating a new plot. I _think_ this is occurring when it encounters a "0" entry in a cell, at which point it apparently stops grabbing new rows. I've included a few screenshots which show this behavior. Note the difference in the P_ELLIPTICAL column between screenshots, where I've manually entered "0" into one of the cells, and the preview plots which contain a different number of points depending on which row the "0" occurs in.

<img width="1303" alt="all_entries" src="https://cloud.githubusercontent.com/assets/20101396/18403392/1fd423a8-76aa-11e6-86a3-a0700b6d18de.png">
<img width="1307" alt="four_entries" src="https://cloud.githubusercontent.com/assets/20101396/18403396/2478efa6-76aa-11e6-8911-2fa49744a9cf.png">
<img width="1303" alt="one_entry" src="https://cloud.githubusercontent.com/assets/20101396/18403397/29d1b866-76aa-11e6-9b58-9dfda093cdf1.png">

**Comment by trouille** [comment]
@srallen Yep, I see this same behavior. You can play with a Google sheet showing a simple scenario of this here:
https://docs.google.com/spreadsheets/d/1LjogC5l-4PpcubQJtCexS2lyucs9bkZpNZRuu4C_5Eg/edit?usp=sharing

Something to note is that when you 'send to sheet' in this scenario, the x-axis no longer has values listed.

**Comment by trouille** [comment]
This is a bug to fix before the 9/21/16 start of the NU course this fall.

**Comment by srallen** [comment]
Reworked how data is retrieved and removed failing conditional.
