### ISSUE TITLE
Histogram tool

### ISSUE THREAD

**Issue by srallen** [amyrebecca/zootools-sheets#54]
- Cannot set overall range for buckets
- Bucket ranges incorrect when data source has negative numbers?

**Comment by trouille** [comment]
Tommy may have found the solution for this. Check in with him before starting on this again.

**Comment by tjnelson5** [comment]
Hi Sarah, 

I think the "rangeStart" variable being defined on line 162 of histogram-script is the problem: I don't think we need this variable to be defined, and it is being reset to zero if all the values are positive.  

If we want some breathing room before the first bucket, we could subtract bucketSize from min.

**Comment by srallen** [comment]
Fixed in latest release.
