### ISSUE TITLE
For the Project builder projects, streamlining export

### ISSUE THREAD

**Issue by JulieAnnKU** [amyrebecca/zootools-sheets#58]
We need something to include the python scripts that Tommy and Cody wrote to aggregate the data for the Galaxy Zoo 101 activity and Hubble's Law activity, so future instructors can just acquire what they need without extra work. We can not expect them to be able to run a python script.

**Comment by trouille** [comment]
Rewritten as https://github.com/zooniverse/intro2astro-server/issues/2
