### ISSUE TITLE
Student research project milestone submissions - may just need advice from dev team

### ISSUE THREAD

**Issue by JulieAnnKU** [amyrebecca/zootools-sheets#60]
Can we design something for students to submit via a google form the milestone pieces to the research project? It would be great if this went to a folder with easy access for the instructor. They would need to submit the following:

- Introductory activity: google doc and sheet

- Research question and hypothesis: could fill in a form

- Key Plots: google sheet and slides

- Videos: video file that could then be shared to other students for peer review

- Peer review: could fill in a form

**Comment by trouille** [comment]
Closing - this would be part of future grant effort if want to find generalized solutions.
