### ISSUE TITLE
"The OAuth identity of this script has been deleted or disabled."

### ISSUE THREAD

**Issue by jrka** [amyrebecca/zootools-sheets#67]
Hi there, 

I seem to have installed Zoo Tools just fine on both my school Google Drive as well as through my personal email account. However, when I actually try to use one of the tools (by going to Add-Ons --> Zoo Tools for Sheets --> and choosing anyone of the helpers), I get this error message:

"The OAuth identity of this script has been deleted or disabled. This may be due to a Terms of Service violation."

When I hit "Details" on the error message, I just get the same text. This is true for both my school and personal gmail accounts, which makes me think it is not a permission error on the part of my institution. I'm on a Mac using an up to date version of Chrome.

Any help would be appreciated, as I plan to have my students using these tools in the next few days. Thanks!

**Comment by srallen** [comment]
@jrka Thanks for your report. The add-on is under review at the moment by Google. There was an issue with the approval for use with Google's APIs, so I'm actively working to get it resolved. Right now I'm waiting on a response from Google which I hope to be any day now. 

If the issue had been with your school's domain, the error would have stated that it was a permission issue with your domain.

I'll respond here as soon as Google authorizes the add-on and I apologize for the interruption in service. It's really bad timing after the AAS presentation for sure!

**Comment by jrka** [comment]
@srallen, have you heard back from Google about this? Any update would be helpful right now for planning purposes.

**Comment by srallen** [comment]
@jrka I've been going back and forth with them regularly. On their end it appears to be approved, but I'm still seeing errors, so it's in the process of troubleshooting unfortunately. 

Something to keep in mind is that the sheets add-on is a tool for building plots without knowing A1 spreadsheet notation, but the built in Google Sheets plotting is quite good and does also generate suggested plots based on the data in the sheet. It's possible to do the activities without the add-on, though, we haven't documented the instructor's guide as such.

**Comment by srallen** [comment]
@jrka We have an identical copy of Zoo Tools for Google Sheets now available on the Add-on store that can be used: https://chrome.google.com/webstore/detail/zoo-tools-for-google-shee/fahnglbfamicnajdcloniiikdmngihgi?authuser=0

Please install this version. The old version will be unpublished soon because the bug with it is on Google's side and I don't know when it'll be resolved.
