### ISSUE TITLE
Last row being excluded from scatter plots?

### ISSUE THREAD

**Issue by jrka** [amyrebecca/zootools-sheets#70]
My students did the HR diagram lab today and found a weird bug. 

Using the Scatter Plot Helper, all the data seems to appear just fine in the "preview" version in the sidebar. But after you click "Send to Sheet," the data point from the last row of data is missing. Even if you re-scale both axes, the last data point is simply not there.

Also, when I tried to flip the axes of a variable by selecting "Invert," it shows up correctly in the preview sidebar, but when sent to sheet, the axis is no longer inverted. This wasn't a big deal since the students weren't plotting their own CMDs, but probably still a bug to fix.

**Comment by srallen** [comment]
@jrka could you share with me a copy of the google spreadsheet where this is happening? Thanks!

**Comment by jrka** [comment]
If it's still useful, it happens all the time, here's just some random data: 

https://docs.google.com/spreadsheets/d/1SB7Ul4YltPkxEwGHhMp1_QsZxMvcdO3uMO8zjrbHy7o/edit?usp=sharing

The two plots under "charts" don't include the data point at (40, 10). One was supposed to have inverted y-axis, but it doesn't when sent to sheet.

**Comment by srallen** [comment]
@jrka Thank you. I will take a look regarding the missing row when I have time hopefully soon.

The axis inversion is actually a known bug that I've reported to Google (https://issuetracker.google.com/issues/67310377). It's been assigned and categorized by them, but I have no other update yet. 

If you really need working axis inversion, you could export the data from Google Sheets to use plotting tools in other spreadsheet apps.

In Office 365: https://support.office.com/en-gb/article/change-the-plotting-order-of-categories-values-or-data-series-94108634-ddb1-409a-9a4d-13f57e6e6df5

Using plot.ly, the last time I tried it, it can be changed updating a toggle in the json representation of the data settings, but that might be a bit to involved for classroom use.

**Comment by srallen** [comment]
@jrka I just requested access to the example sheet with the bug you describe of the last row being left off the scatter plot chart. Could you please grant access? Thanks!

**Comment by srallen** [comment]
@jrka I believe I fixed the issue with the last row being left off when the chart is sent to the sheet. Please try it out and let me know if it is indeed fixed for you.

**Comment by jrka** [comment]
It works for me now!
